name: Weingut Test
favicon: null
layout_spectrum: 0.56051
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e20814'
    - '#000000'
    - '#b8b9b8'
    - '#f2a1a5'
  brandStrength: 0.49912113160826266
  lightness: 0.5177207589149475
  saturation: 0.35366410738788545
  rhythmicContrast: 0.44478427874855697
purpose: []
