name: Weingut Test
favicon: null
layout_spectrum: 0.87598
typography_spectrum: 0.79771
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcd6cb'
    - '#ffffff'
    - '#a58f81'
    - '#080302'
    - '#83352e'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
